export const icons = {
  person: require("../../assets/icons/person.png"),
  email: require("../../assets/icons/email.png"),
  lock: require("../../assets/icons/lock.png"),
  google: require("../../assets/icons/google.png"),
  eyecross: require("../../assets/icons/eyecross.png"),
  home: require("../../assets/icons/home.png"),
  list: require("../../assets/icons/list.png"),
  chat: require("../../assets/icons/chat.png"),
  profile: require("../../assets/icons/profile.png"),
  to: require("../../assets/icons/to.png"),
  point: require("../../assets/icons/point.png"),
  out: require("../../assets/icons/out.png"),
  search: require("../../assets/icons/search.png"),
  marker: require("../../assets/icons/marker.png"),
  selectedMarker: require("../../assets/icons/selected-marker.png"),
};
